module.exports = {
	range: false,
	loc: false,
	comments: false,
	attachComment: false,
	tokens: false,
	tolerant: true,
	ecmaFeatures: {
		arrowFunctions: true,
		blockBindings: true,
		destructuring: true,
		regexYFlag: true,
		regexUFlag: true,
		templateStrings: true,
		binaryLiterals: true,
		octalLiterals: true,
		unicodeCodePointEscapes: true,
		defaultParams: true,
		restParams: true,
		forOf: true,
		objectLiteralComputedProperties: true,
		objectLiteralShorthandMethods: true,
		objectLiteralShorthandProperties: true,
		objectLiteralDuplicateProperties: true,
		generators: true,
		spread: true,
		superInFunctions: true,
		classes: true,
		newTarget: false,
		modules: true,
		jsx: true,
		globalReturn: true,
		experimentalObjectRestSpread: true
	}
};
