root: true

plugins:
    - react
    - jsx-a11y

extends:
    - eslint
    - plugin:react/recommended
    - plugin:jsx-a11y/recommended

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        jsx: true

env:
    browser: true
    amd: true

globals:
    _: false
    $: false

rules:
    # Disable rules that assume an ES6 environment.
    # This is not a complete list. More rules should be added as problems are encountered.
    no-var: off
    object-shorthand: off
    prefer-arrow-callback: off
    prefer-template: off

    # Disable rules that the codebase doesn't currently follow.
    # It might be a good idea to enable these in the future.
    jsx-a11y/no-onchange: off
    react/prop-types: off
    require-jsdoc: off

settings:
    react:
        version: 15.0.1
